# Generated by Django 2.0.13 on 2020-03-18 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Numero', models.CharField(max_length=30, unique=True)),
                ('Orden_de_Compra_Nro', models.CharField(max_length=40)),
                ('Observaciones', models.TextField(blank=True, max_length=100)),
                ('Estado', models.CharField(blank=True, choices=[('PREPARANDO CERTIFICACION', 'PREPARANDO CERTIFICACION'), ('FIRMADO', 'FIRMADO'), ('FACTURADO', 'FACTURADO'), ('COBRADO', 'COBRADO')], max_length=40)),
                ('Sistema', models.CharField(blank=True, choices=[('CALDERA', 'CALDERA'), ('ENFRIAMIENTO', 'ENFRIAMIENTO'), ('CALDERA/ENFRIAMIENTO', 'CALDERA/ENFRIAMIENTO')], max_length=20)),
            ],
            options={
                'ordering': ['-Fecha'],
            },
        ),
        migrations.CreateModel(
            name='Cliente_Proveedor',
            fields=[
                ('tipo', models.CharField(blank=True, choices=[('Cliente', 'Cliente'), ('Proveedor', 'Proveedor')], max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('e_mail', models.CharField(max_length=30)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=20)),
                ('unidad', models.IntegerField()),
                ('Cantidad', models.IntegerField(editable=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('envase', models.IntegerField(null=True)),
                ('procedencia', models.CharField(max_length=3)),
                ('producto', models.CharField(max_length=100, unique=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('stockCritico', models.IntegerField()),
                ('kg', models.IntegerField(default=1, editable=False)),
                ('Observaciones', models.TextField(blank=True, max_length=100)),
                ('Vencimiento', models.DateField()),
                ('Critico', models.CharField(default=1, editable=False, max_length=30)),
                ('asterisco', models.CharField(choices=[('X', 'X'), ('.', '.')], max_length=2, null=True)),
            ],
            options={
                'ordering': ['producto'],
            },
        ),
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Numero', models.CharField(max_length=30, unique=True)),
                ('Orden_de_Compra_Nro', models.CharField(max_length=40)),
                ('Estado', models.CharField(blank=True, choices=[('PREPARANDO REMITO', 'PREPARANDO REMITO'), ('RETIRADO', 'RETIRADO'), ('ENTREGADO', 'ENTREGADO'), ('FACTURADO', 'FACTURADO'), ('COBRADO', 'COBRADO'), ('AJUSTE STOCK', 'AJUSTE STOCK'), ('INGRESO RECIBIDO', 'INGRESO RECIBIDO')], max_length=20)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Lote', models.CharField(blank=True, max_length=20)),
                ('Valor_Declarado', models.CharField(max_length=100)),
                ('Flete', models.CharField(max_length=20, verbose_name=' Flete a Cargo')),
                ('Retira', models.CharField(max_length=20)),
                ('Observaciones', models.TextField(blank=True, max_length=100)),
                ('Cliente_o_Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Cliente_Proveedor')),
            ],
            options={
                'ordering': ['-Fecha'],
            },
        ),
        migrations.AddField(
            model_name='movimientos',
            name='Remito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Remito'),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Producto'),
        ),
        migrations.AddField(
            model_name='certificaciones',
            name='Cliente_o_Proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Cliente_Proveedor'),
        ),
        migrations.AddField(
            model_name='certificaciones',
            name='remito',
            field=models.ManyToManyField(to='Inventory.Remito'),
        ),
    ]
