# Generated by Django 3.0.4 on 2020-04-08 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20200403_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='Remito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='Inventory.Remito'),
        ),
    ]
